image: node:lts-alpine

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  mongoServer: "mongo:27017"

stages:
  - test
  - audit

test:
  stage: test
  except:
    - schedules
  services:
    - mongo:latest
  script:
    - apk add --no-cache build-base python3 libtool autoconf automake
      # npm private token
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn test:ci
  coverage: '/^Statements\s*:\s*([^%]+)/'

audit:
  stage: audit
  only:
  - schedules
  script:
    - yarn audit
